apiVersion: v1
kind: Namespace
metadata:
  name: ${KUBEVIRT_NAMESPACE}
  labels:
    initial-deploy-with-kubectl: "true"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubevirt
  namespace: ${KUBEVIRT_NAMESPACE}
spec:
  project: cluster-services
  destination:
    namespace: ${KUBEVIRT_NAMESPACE}
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
    retry:
      limit: 10
      backoff:
        duration: 20s
        factor: 2
        maxDuration: 10m
  sources:
    - repoURL: ${GITEA_CLUSTER_SERVICES_REPO_URL}
      targetRevision: ${GITEA_CLUSTER_SERVICES_REPO_BRANCH}
      path: rendered/${OVERLAY_NAME}/kubevirt
