apiVersion: v1
kind: Namespace
metadata:
  name: ${GITEA_NAMESPACE}
  labels:
    initial-deploy-with-kubectl: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: ${GITEA_NAMESPACE}-runners
  labels:
    initial-deploy-with-kubectl: "true"
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea
  namespace: ${GITEA_NAMESPACE}
  annotations:
      argocd.argoproj.io/sync-wave: "5"  # Deploy after CNPG cluster has time to become ready
spec:
  project: cluster-services
  destination:
    namespace: ${GITEA_NAMESPACE}
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=false
    retry:
      limit: 10
      backoff:
        duration: 20s
        factor: 2
        maxDuration: 10m
  sources:
    - chart: gitea
      repoURL: https://dl.gitea.com/charts/
      targetRevision: ${GITEA_HELM_VERSION}
      helm:
        releaseName: gitea
        valueFiles:
          - $values/_rendered/gitea/giteaValues.yaml
    - repoURL: ${GITEA_CLUSTER_SERVICES_REPO_URL}
      targetRevision: ${GITEA_CLUSTER_SERVICES_REPO_BRANCH}
      ref: values
      path: _rendered/gitea
      directory:
        recurse: false
        include: "{giteaSecretsBootstrap.yaml,giteaRunnerTokenBootstrap.yaml}"

