apiVersion: v1
kind: Namespace
metadata:
  name: ${RELOADER_NAMESPACE}
  labels:
    initial-deploy-with-kubectl: "true"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reloader
  namespace: ${RELOADER_NAMESPACE}
spec:
  project: cluster-services
  destination:
    server: https://kubernetes.default.svc
    namespace: ${RELOADER_NAMESPACE}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
    retry:
      limit: 10
      backoff:
        duration: 20s
        factor: 2
        maxDuration: 10m
  sources:
    - chart: reloader
      repoURL: https://stakater.github.io/stakater-charts
      targetRevision: ${RELOADER_HELM_VERSION}
      helm:
        releaseName: reloader
        valueFiles:
          - $values/_rendered/reloader/reloaderValues.yaml
    - repoURL: ${GITEA_CLUSTER_SERVICES_REPO_URL}
      targetRevision: ${GITEA_CLUSTER_SERVICES_REPO_BRANCH}
      ref: values
      path: _rendered/reloader
