#TODO See if this new chart can be used: https://gitea.com/gitea/helm-actions
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea-runners
  namespace: ${GITEA_NAMESPACE}-runners
  annotations:
      argocd.argoproj.io/sync-wave: "10"  # Deploy after Gitea
spec:
  project: cluster-services
  destination:
    namespace: ${GITEA_NAMESPACE}-runners
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=false
    retry:
      limit: 10
      backoff:
        duration: 20s
        factor: 2
        maxDuration: 10m
  sources:

    - repoURL: https://gitea.com/anders.eficode/helm-actions-hostusers.git
      path: .
      targetRevision: main
      helm:
        releaseName: gitea-runners
        valueFiles:
          - $values/_rendered/gitea-runners/giteaRunnersHelmValues.yaml

    # Switch to below once merged: https://gitea.com/gitea/helm-actions/pulls/160
    # Switch to below once merged: https://gitea.com/gitea/helm-actions/pulls/160
    # Switch to below once merged: https://gitea.com/gitea/helm-actions/pulls/160
    # - chart: actions
    #   repoURL: https://dl.gitea.com/charts/
    #   targetRevision: ${GITEA_RUNNERS_HELM_VERSION}
    #   helm:
    #     releaseName: gitea-runners
    #     valueFiles:
    #       - $values/_rendered/gitea-runners/giteaRunnersHelmValues.yaml

    - repoURL: ${GITEA_CLUSTER_SERVICES_REPO_URL}
      targetRevision: ${GITEA_CLUSTER_SERVICES_REPO_BRANCH}
      ref: values
      path: _rendered/gitea-runners
      directory:
        recurse: false
        include: "{giteaRunnerServiceAccount.yaml,giteaRunnerConfigMaps.yaml}"