apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea-runners
  namespace: ${GITEA_NAMESPACE}-runners
  annotations:
      argocd.argoproj.io/sync-wave: "10"  # Deploy after Gitea
spec:
  project: cluster-services
  destination:
    namespace: ${GITEA_NAMESPACE}-runners
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=false
    retry:
      limit: 10
      backoff:
        duration: 20s
        factor: 2
        maxDuration: 10m
  sources:
    - repoURL: ${GITEA_CLUSTER_SERVICES_REPO_URL}
      targetRevision: ${GITEA_CLUSTER_SERVICES_REPO_BRANCH}
      ref: values
      path: _rendered/gitea-runners
      directory:
        recurse: false
        include: "{giteaRunnerServiceAccount.yaml,giteaRunnerConfigMaps.yaml,giteaRunnersDeployment.yaml}"
