apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: kube-system
spec:
  project: cluster-services
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  # Ignore differences in specific fields to prevent false out-of-sync
  ignoreDifferences:
    # Similar issue documented here: https://github.com/kedacore/keda/discussions/5123
    # Basically the default value is "False" but the chart sets it to "nil" which causes ArgoCD to think it's out of sync
    - group: apiregistration.k8s.io
      kind: APIService
      jqPathExpressions:
        - .spec.insecureSkipTLSVerify

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=false
    retry:
      limit: 10
      backoff:
        duration: 20s
        factor: 2
        maxDuration: 10m
  sources:
    - chart: metrics-server
      repoURL: https://kubernetes-sigs.github.io/metrics-server/ #https://artifacthub.io/packages/helm/metrics-server/metrics-server
      targetRevision: ${METRICS_SERVER_HELM_VERSION}
      helm:
        releaseName: metrics-server
        valueFiles:
          - $values/_rendered/metrics-server/metricsServerHelmValues.yaml
    - repoURL: ${GITEA_CLUSTER_SERVICES_REPO_URL}
      targetRevision: ${GITEA_CLUSTER_SERVICES_REPO_BRANCH}
      ref: values

