apiVersion: v1
kind: Namespace
metadata:
  name: external-dns
  labels:
    initial-deploy-with-kubectl: "true"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: external-dns
  annotations:
    argocd.argoproj.io/sync-wave: "5"  # Deploy after networking and ingress controllers
spec:
  project: cluster-services
  destination:
    namespace: external-dns
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=false
    retry:
      limit: 10
      backoff:
        duration: 20s
        factor: 2
        maxDuration: 10m
  sources:
    - chart: external-dns
      repoURL: https://kubernetes-sigs.github.io/external-dns/
      targetRevision: ${EXTERNAL_DNS_HELM_VERSION}
      helm:
        releaseName: external-dns
        valueFiles:
          - $values/_rendered/external-dns/externalDnsHelmValues.yaml
    - repoURL: ${GITEA_CLUSTER_SERVICES_REPO_URL}
      targetRevision: ${GITEA_CLUSTER_SERVICES_REPO_BRANCH}
      path: _rendered/external-dns
      ref: values
      directory:
        recurse: false
        exclude: "{externalDnsHelmValues.yaml,externalDnsArgoApp.yaml}"  # Exclude the TSIG secret, since we are using Pihole instead of RFC2136 and don't need it
