apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager-csi
  labels:
    initial-deploy-with-kubectl: "true"
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-csi
  namespace: $CERT_MGR_CSI_NAMESPACE
spec:
  project: cluster-services
  destination:
    server: https://kubernetes.default.svc
    namespace: $CERT_MGR_CSI_NAMESPACE
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 10
      backoff:
        duration: 20s
        factor: 2
        maxDuration: 10m
  sources:
    - chart: cert-manager-csi-driver
      repoURL: quay.io/jetstack/charts
      targetRevision: ${CERT_MGR_CSI_HELM_VERSION}
      helm:
        releaseName: cert-manager-csi-driver
        valueFiles:
          - $values/_rendered/cert-manager/certManagerCsiValues.yaml
    - repoURL: $GITEA_CLUSTER_SERVICES_REPO_URL
      targetRevision: ${GITEA_CLUSTER_SERVICES_REPO_BRANCH}
      ref: values